export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
}

export interface EmojiData {
  [key: string]: EmojiItem[];
}

export const emojiData: EmojiData = {
  smileys: [
    { emoji: '😀', name: 'grinning face', keywords: ['smile', 'happy', 'joy'] },
    { emoji: '😃', name: 'grinning face with big eyes', keywords: ['smile', 'happy', 'joy'] },
    { emoji: '😄', name: 'grinning face with smiling eyes', keywords: ['smile', 'happy', 'joy'] },
    { emoji: '😁', name: 'beaming face with smiling eyes', keywords: ['smile', 'happy', 'grin'] },
    { emoji: '😆', name: 'grinning squinting face', keywords: ['laugh', 'happy', 'satisfied'] },
    { emoji: '😅', name: 'grinning face with sweat', keywords: ['hot', 'happy', 'laugh', 'relief'] },
    { emoji: '🤣', name: 'rolling on the floor laughing', keywords: ['laugh', 'lol', 'rofl'] },
    { emoji: '😂', name: 'face with tears of joy', keywords: ['laugh', 'cry', 'tears', 'lol'] },
    { emoji: '🙂', name: 'slightly smiling face', keywords: ['smile', 'happy'] },
    { emoji: '🙃', name: 'upside-down face', keywords: ['silly', 'sarcasm'] },
    { emoji: '😉', name: 'winking face', keywords: ['wink', 'flirt'] },
    { emoji: '😊', name: 'smiling face with smiling eyes', keywords: ['smile', 'happy', 'blush'] },
    { emoji: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent', 'halo'] },
    { emoji: '🥰', name: 'smiling face with hearts', keywords: ['love', 'hearts', 'adore'] },
    { emoji: '😍', name: 'smiling face with heart-eyes', keywords: ['love', 'heart', 'eyes'] },
    { emoji: '🤩', name: 'star-struck', keywords: ['star', 'eyes', 'excited'] },
    { emoji: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love', 'heart'] },
    { emoji: '😗', name: 'kissing face', keywords: ['kiss', 'love'] },
    { emoji: '😚', name: 'kissing face with closed eyes', keywords: ['kiss', 'love'] },
    { emoji: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss', 'love', 'smile'] },
    { emoji: '😋', name: 'face savoring food', keywords: ['yum', 'delicious', 'food'] },
    { emoji: '😛', name: 'face with tongue', keywords: ['tongue', 'silly'] },
    { emoji: '😜', name: 'winking face with tongue', keywords: ['wink', 'tongue', 'silly'] },
    { emoji: '🤪', name: 'zany face', keywords: ['crazy', 'goofy', 'wild'] },
    { emoji: '😝', name: 'squinting face with tongue', keywords: ['tongue', 'silly', 'playful'] },
    { emoji: '🤑', name: 'money-mouth face', keywords: ['money', 'rich', 'dollar'] },
    { emoji: '🤗', name: 'hugging face', keywords: ['hug', 'embrace'] },
    { emoji: '🤭', name: 'face with hand over mouth', keywords: ['oops', 'surprise', 'giggle'] },
    { emoji: '🤫', name: 'shushing face', keywords: ['shh', 'quiet', 'secret'] },
    { emoji: '🤔', name: 'thinking face', keywords: ['think', 'hmm', 'consider'] },
    { emoji: '🤐', name: 'zipper-mouth face', keywords: ['zipper', 'secret', 'silent'] },
    { emoji: '🤨', name: 'face with raised eyebrow', keywords: ['suspicious', 'skeptical'] },
    { emoji: '😐', name: 'neutral face', keywords: ['neutral', 'meh', 'blank'] },
    { emoji: '😑', name: 'expressionless face', keywords: ['blank', 'neutral', 'meh'] },
    { emoji: '😶', name: 'face without mouth', keywords: ['silent', 'speechless'] },
    { emoji: '😏', name: 'smirking face', keywords: ['smirk', 'confident'] },
    { emoji: '😒', name: 'unamused face', keywords: ['annoyed', 'unimpressed'] },
    { emoji: '🙄', name: 'face with rolling eyes', keywords: ['roll', 'eyes', 'annoyed'] },
    { emoji: '😬', name: 'grimacing face', keywords: ['awkward', 'nervous'] },
    { emoji: '🤥', name: 'lying face', keywords: ['lie', 'pinocchio', 'liar'] },
    { emoji: '😌', name: 'relieved face', keywords: ['relief', 'calm', 'peace'] },
    { emoji: '😔', name: 'pensive face', keywords: ['sad', 'depressed', 'thoughtful'] },
    { emoji: '😪', name: 'sleepy face', keywords: ['tired', 'sleep', 'sleepy'] },
    { emoji: '🤤', name: 'drooling face', keywords: ['drool', 'hungry'] },
    { emoji: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz', 'tired'] },
    { emoji: '😷', name: 'face with medical mask', keywords: ['mask', 'sick', 'doctor'] },
    { emoji: '🤒', name: 'face with thermometer', keywords: ['sick', 'ill', 'fever'] },
    { emoji: '🤕', name: 'face with head-bandage', keywords: ['hurt', 'injured', 'bandage'] },
    { emoji: '🤢', name: 'nauseated face', keywords: ['sick', 'nauseous', 'gross'] },
    { emoji: '🤮', name: 'face vomiting', keywords: ['sick', 'vomit', 'puke'] },
    { emoji: '🤧', name: 'sneezing face', keywords: ['sneeze', 'sick', 'achoo'] },
    { emoji: '🥵', name: 'hot face', keywords: ['hot', 'heat', 'sweat'] },
    { emoji: '🥶', name: 'cold face', keywords: ['cold', 'freezing', 'frozen'] },
    { emoji: '😵', name: 'dizzy face', keywords: ['dizzy', 'confused', 'spiral'] },
    { emoji: '🤯', name: 'exploding head', keywords: ['mind', 'blown', 'shocked'] },
    { emoji: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'hat', 'western'] },
    { emoji: '🥳', name: 'partying face', keywords: ['party', 'celebration', 'hat'] },
    { emoji: '😎', name: 'smiling face with sunglasses', keywords: ['cool', 'sunglasses', 'confident'] },
    { emoji: '🤓', name: 'nerd face', keywords: ['nerd', 'geek', 'glasses'] },
    { emoji: '🧐', name: 'face with monocle', keywords: ['monocle', 'curious', 'fancy'] },
    { emoji: '😕', name: 'confused face', keywords: ['confused', 'puzzled'] },
    { emoji: '😟', name: 'worried face', keywords: ['worried', 'concerned'] },
    { emoji: '🙁', name: 'slightly frowning face', keywords: ['sad', 'frown'] },
    { emoji: '☹️', name: 'frowning face', keywords: ['sad', 'frown', 'unhappy'] },
    { emoji: '😮', name: 'face with open mouth', keywords: ['wow', 'surprised', 'amazed'] },
    { emoji: '😯', name: 'hushed face', keywords: ['surprised', 'shocked'] },
    { emoji: '😲', name: 'astonished face', keywords: ['shocked', 'amazed', 'gasp'] },
    { emoji: '😳', name: 'flushed face', keywords: ['blush', 'embarrassed'] },
    { emoji: '🥺', name: 'pleading face', keywords: ['puppy', 'eyes', 'beg', 'please'] },
    { emoji: '😦', name: 'frowning face with open mouth', keywords: ['sad', 'worried'] },
    { emoji: '😧', name: 'anguished face', keywords: ['anguish', 'stunned'] },
    { emoji: '😨', name: 'fearful face', keywords: ['fear', 'scared', 'afraid'] },
    { emoji: '😰', name: 'anxious face with sweat', keywords: ['nervous', 'anxious', 'sweat'] },
    { emoji: '😥', name: 'sad but relieved face', keywords: ['sad', 'relief', 'phew'] },
    { emoji: '😢', name: 'crying face', keywords: ['cry', 'sad', 'tear'] },
    { emoji: '😭', name: 'loudly crying face', keywords: ['cry', 'sob', 'tears'] },
    { emoji: '😱', name: 'face screaming in fear', keywords: ['scream', 'scared', 'shock'] },
    { emoji: '😖', name: 'confounded face', keywords: ['confused', 'frustrated'] },
    { emoji: '😣', name: 'persevering face', keywords: ['struggle', 'persevere'] },
    { emoji: '😞', name: 'disappointed face', keywords: ['disappointed', 'sad'] },
    { emoji: '😓', name: 'downcast face with sweat', keywords: ['sweat', 'sad', 'tired'] },
    { emoji: '😩', name: 'weary face', keywords: ['tired', 'weary', 'exhausted'] },
    { emoji: '😫', name: 'tired face', keywords: ['tired', 'exhausted', 'fed up'] },
    { emoji: '🥱', name: 'yawning face', keywords: ['yawn', 'tired', 'bored'] },
    { emoji: '😤', name: 'face with steam from nose', keywords: ['angry', 'frustrated', 'triumph'] },
    { emoji: '😡', name: 'pouting face', keywords: ['angry', 'mad', 'annoyed'] },
    { emoji: '😠', name: 'angry face', keywords: ['angry', 'mad', 'annoyed'] },
    { emoji: '🤬', name: 'face with symbols on mouth', keywords: ['cursing', 'swearing', 'angry'] },
    { emoji: '😈', name: 'smiling face with horns', keywords: ['devil', 'evil', 'mischief'] },
    { emoji: '👿', name: 'angry face with horns', keywords: ['devil', 'evil', 'angry'] },
    { emoji: '💀', name: 'skull', keywords: ['skull', 'death', 'dead'] },
    { emoji: '☠️', name: 'skull and crossbones', keywords: ['skull', 'danger', 'poison'] },
    { emoji: '💩', name: 'pile of poo', keywords: ['poop', 'poo', 'crap'] },
    { emoji: '🤡', name: 'clown face', keywords: ['clown', 'funny', 'circus'] },
    { emoji: '👹', name: 'ogre', keywords: ['monster', 'ogre', 'creature'] },
    { emoji: '👺', name: 'goblin', keywords: ['goblin', 'monster', 'creature'] },
    { emoji: '👻', name: 'ghost', keywords: ['ghost', 'spooky', 'halloween'] },
    { emoji: '👽', name: 'alien', keywords: ['alien', 'ufo', 'space'] },
    { emoji: '👾', name: 'alien monster', keywords: ['alien', 'game', 'space'] },
    { emoji: '🤖', name: 'robot', keywords: ['robot', 'machine', 'ai'] },
  ],
  people: [
    { emoji: '👋', name: 'waving hand', keywords: ['wave', 'hello', 'hi', 'bye'] },
    { emoji: '🤚', name: 'raised back of hand', keywords: ['hand', 'stop'] },
    { emoji: '✋', name: 'raised hand', keywords: ['hand', 'stop', 'high five'] },
    { emoji: '👌', name: 'ok hand', keywords: ['ok', 'okay', 'perfect'] },
    { emoji: '✌️', name: 'victory hand', keywords: ['peace', 'victory', 'two'] },
    { emoji: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope', 'wish'] },
    { emoji: '🤟', name: 'love-you gesture', keywords: ['love', 'you', 'hand'] },
    { emoji: '🤘', name: 'sign of the horns', keywords: ['rock', 'metal', 'horns'] },
    { emoji: '🤙', name: 'call me hand', keywords: ['call', 'phone', 'hang loose'] },
    { emoji: '👈', name: 'backhand index pointing left', keywords: ['left', 'point'] },
    { emoji: '👉', name: 'backhand index pointing right', keywords: ['right', 'point'] },
    { emoji: '👆', name: 'backhand index pointing up', keywords: ['up', 'point'] },
    { emoji: '👇', name: 'backhand index pointing down', keywords: ['down', 'point'] },
    { emoji: '☝️', name: 'index pointing up', keywords: ['one', 'up', 'point'] },
    { emoji: '👍', name: 'thumbs up', keywords: ['like', 'yes', 'approve', 'good'] },
    { emoji: '👎', name: 'thumbs down', keywords: ['dislike', 'no', 'bad'] },
    { emoji: '✊', name: 'raised fist', keywords: ['fist', 'power', 'solidarity'] },
    { emoji: '👊', name: 'oncoming fist', keywords: ['fist', 'bump', 'punch'] },
    { emoji: '👏', name: 'clapping hands', keywords: ['clap', 'applause', 'bravo'] },
    { emoji: '🙌', name: 'raising hands', keywords: ['celebrate', 'hooray', 'yay'] },
    { emoji: '👐', name: 'open hands', keywords: ['hands', 'open', 'hug'] },
    { emoji: '🤲', name: 'palms up together', keywords: ['pray', 'please', 'offer'] },
    { emoji: '🤝', name: 'handshake', keywords: ['shake', 'deal', 'agreement'] },
    { emoji: '🙏', name: 'folded hands', keywords: ['pray', 'thanks', 'please', 'namaste'] },
    { emoji: '💪', name: 'flexed biceps', keywords: ['muscle', 'strong', 'flex', 'strength'] },
    { emoji: '👶', name: 'baby', keywords: ['baby', 'infant', 'child'] },
    { emoji: '👧', name: 'girl', keywords: ['girl', 'child', 'kid'] },
    { emoji: '👦', name: 'boy', keywords: ['boy', 'child', 'kid'] },
    { emoji: '👩', name: 'woman', keywords: ['woman', 'female', 'lady'] },
    { emoji: '👨', name: 'man', keywords: ['man', 'male', 'guy'] },
    { emoji: '👵', name: 'old woman', keywords: ['old', 'woman', 'grandma', 'elderly'] },
    { emoji: '👴', name: 'old man', keywords: ['old', 'man', 'grandpa', 'elderly'] },
    { emoji: '👀', name: 'eyes', keywords: ['eyes', 'look', 'watch', 'see'] },
    { emoji: '👁', name: 'eye', keywords: ['eye', 'look', 'watch'] },
    { emoji: '👃', name: 'nose', keywords: ['nose', 'smell'] },
    { emoji: '👄', name: 'mouth', keywords: ['mouth', 'lips', 'kiss'] },
    { emoji: '💋', name: 'kiss mark', keywords: ['kiss', 'lipstick', 'lips'] },
  ],
  animals: [
    { emoji: '🐶', name: 'dog face', keywords: ['dog', 'puppy', 'pet'] },
    { emoji: '🐱', name: 'cat face', keywords: ['cat', 'kitty', 'pet'] },
    { emoji: '🐭', name: 'mouse face', keywords: ['mouse', 'rat'] },
    { emoji: '🐹', name: 'hamster', keywords: ['hamster', 'pet'] },
    { emoji: '🐰', name: 'rabbit face', keywords: ['rabbit', 'bunny'] },
    { emoji: '🦊', name: 'fox', keywords: ['fox', 'animal'] },
    { emoji: '🐻', name: 'bear', keywords: ['bear', 'animal'] },
    { emoji: '🐼', name: 'panda', keywords: ['panda', 'bear'] },
    { emoji: '🐨', name: 'koala', keywords: ['koala', 'bear'] },
    { emoji: '🐯', name: 'tiger face', keywords: ['tiger', 'cat'] },
    { emoji: '🦁', name: 'lion', keywords: ['lion', 'cat', 'king'] },
    { emoji: '🐮', name: 'cow face', keywords: ['cow', 'cattle'] },
    { emoji: '🐷', name: 'pig face', keywords: ['pig', 'pork'] },
    { emoji: '🐸', name: 'frog', keywords: ['frog', 'toad'] },
    { emoji: '🐵', name: 'monkey face', keywords: ['monkey', 'ape'] },
    { emoji: '🙈', name: 'see-no-evil monkey', keywords: ['monkey', 'see', 'no', 'evil'] },
    { emoji: '🙉', name: 'hear-no-evil monkey', keywords: ['monkey', 'hear', 'no', 'evil'] },
    { emoji: '🙊', name: 'speak-no-evil monkey', keywords: ['monkey', 'speak', 'no', 'evil'] },
    { emoji: '🐔', name: 'chicken', keywords: ['chicken', 'bird'] },
    { emoji: '🐧', name: 'penguin', keywords: ['penguin', 'bird'] },
    { emoji: '🐦', name: 'bird', keywords: ['bird', 'fly'] },
    { emoji: '🐤', name: 'baby chick', keywords: ['chick', 'baby', 'bird'] },
    { emoji: '🦆', name: 'duck', keywords: ['duck', 'bird'] },
    { emoji: '🦅', name: 'eagle', keywords: ['eagle', 'bird'] },
    { emoji: '🦉', name: 'owl', keywords: ['owl', 'bird', 'wise'] },
    { emoji: '🐝', name: 'honeybee', keywords: ['bee', 'honey', 'buzz'] },
    { emoji: '🐛', name: 'bug', keywords: ['bug', 'insect', 'worm'] },
    { emoji: '🦋', name: 'butterfly', keywords: ['butterfly', 'insect', 'beautiful'] },
    { emoji: '🐌', name: 'snail', keywords: ['snail', 'slow'] },
    { emoji: '🐞', name: 'lady beetle', keywords: ['ladybug', 'insect'] },
    { emoji: '🐜', name: 'ant', keywords: ['ant', 'insect'] },
    { emoji: '🐢', name: 'turtle', keywords: ['turtle', 'slow'] },
    { emoji: '🐍', name: 'snake', keywords: ['snake', 'reptile'] },
    { emoji: '🦎', name: 'lizard', keywords: ['lizard', 'reptile'] },
    { emoji: '🐙', name: 'octopus', keywords: ['octopus', 'sea'] },
    { emoji: '🦑', name: 'squid', keywords: ['squid', 'sea'] },
    { emoji: '🐠', name: 'tropical fish', keywords: ['fish', 'tropical', 'sea'] },
    { emoji: '🐟', name: 'fish', keywords: ['fish', 'sea'] },
    { emoji: '🐬', name: 'dolphin', keywords: ['dolphin', 'sea', 'smart'] },
    { emoji: '🐳', name: 'spouting whale', keywords: ['whale', 'sea', 'spout'] },
    { emoji: '🐋', name: 'whale', keywords: ['whale', 'sea', 'big'] },
    { emoji: '🦈', name: 'shark', keywords: ['shark', 'sea', 'danger'] },
    { emoji: '🐘', name: 'elephant', keywords: ['elephant', 'big', 'trunk'] },
    { emoji: '🦒', name: 'giraffe', keywords: ['giraffe', 'tall', 'long neck'] },
    { emoji: '🦘', name: 'kangaroo', keywords: ['kangaroo', 'jump', 'australia'] },
    { emoji: '🐎', name: 'horse', keywords: ['horse', 'fast', 'racing'] },
    { emoji: '🦌', name: 'deer', keywords: ['deer', 'antlers'] },
    { emoji: '🐕', name: 'dog', keywords: ['dog', 'pet', 'puppy'] },
    { emoji: '🐈', name: 'cat', keywords: ['cat', 'pet', 'kitty'] },
    { emoji: '🐓', name: 'rooster', keywords: ['rooster', 'chicken', 'morning'] },
    { emoji: '🦃', name: 'turkey', keywords: ['turkey', 'bird', 'thanksgiving'] },
    { emoji: '🐇', name: 'rabbit', keywords: ['rabbit', 'bunny', 'fast'] },
  ],
  food: [
    { emoji: '🍏', name: 'green apple', keywords: ['apple', 'fruit', 'green'] },
    { emoji: '🍎', name: 'red apple', keywords: ['apple', 'fruit', 'red'] },
    { emoji: '🍐', name: 'pear', keywords: ['pear', 'fruit'] },
    { emoji: '🍊', name: 'tangerine', keywords: ['orange', 'fruit', 'citrus'] },
    { emoji: '🍋', name: 'lemon', keywords: ['lemon', 'fruit', 'citrus', 'sour'] },
    { emoji: '🍌', name: 'banana', keywords: ['banana', 'fruit', 'yellow'] },
    { emoji: '🍉', name: 'watermelon', keywords: ['watermelon', 'fruit', 'summer'] },
    { emoji: '🍇', name: 'grapes', keywords: ['grapes', 'fruit', 'wine'] },
    { emoji: '🍓', name: 'strawberry', keywords: ['strawberry', 'fruit', 'berry'] },
    { emoji: '🍒', name: 'cherries', keywords: ['cherry', 'fruit', 'red'] },
    { emoji: '🍑', name: 'peach', keywords: ['peach', 'fruit'] },
    { emoji: '🥭', name: 'mango', keywords: ['mango', 'fruit', 'tropical'] },
    { emoji: '🍍', name: 'pineapple', keywords: ['pineapple', 'fruit', 'tropical'] },
    { emoji: '🥥', name: 'coconut', keywords: ['coconut', 'fruit', 'tropical'] },
    { emoji: '🥝', name: 'kiwi fruit', keywords: ['kiwi', 'fruit', 'green'] },
    { emoji: '🍅', name: 'tomato', keywords: ['tomato', 'vegetable', 'red'] },
    { emoji: '🍆', name: 'eggplant', keywords: ['eggplant', 'vegetable', 'purple'] },
    { emoji: '🥑', name: 'avocado', keywords: ['avocado', 'fruit', 'green', 'healthy'] },
    { emoji: '🥦', name: 'broccoli', keywords: ['broccoli', 'vegetable', 'green'] },
    { emoji: '🥕', name: 'carrot', keywords: ['carrot', 'vegetable', 'orange'] },
    { emoji: '🌽', name: 'ear of corn', keywords: ['corn', 'vegetable', 'yellow'] },
    { emoji: '🌶', name: 'hot pepper', keywords: ['pepper', 'spicy', 'hot', 'chili'] },
    { emoji: '🥔', name: 'potato', keywords: ['potato', 'vegetable'] },
    { emoji: '🍞', name: 'bread', keywords: ['bread', 'loaf', 'carbs'] },
    { emoji: '🥐', name: 'croissant', keywords: ['croissant', 'bread', 'french'] },
    { emoji: '🥖', name: 'baguette bread', keywords: ['baguette', 'bread', 'french'] },
    { emoji: '🧀', name: 'cheese wedge', keywords: ['cheese', 'dairy'] },
    { emoji: '🥚', name: 'egg', keywords: ['egg', 'protein', 'breakfast'] },
    { emoji: '🍳', name: 'cooking', keywords: ['egg', 'cooking', 'fry', 'breakfast'] },
    { emoji: '🥓', name: 'bacon', keywords: ['bacon', 'meat', 'breakfast'] },
    { emoji: '🥩', name: 'cut of meat', keywords: ['meat', 'steak', 'protein'] },
    { emoji: '🍗', name: 'poultry leg', keywords: ['chicken', 'meat', 'drumstick'] },
    { emoji: '🍖', name: 'meat on bone', keywords: ['meat', 'bone', 'ribs'] },
    { emoji: '🌭', name: 'hot dog', keywords: ['hotdog', 'sausage', 'fast food'] },
    { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'hamburger', 'fast food'] },
    { emoji: '🍟', name: 'french fries', keywords: ['fries', 'potato', 'fast food'] },
    { emoji: '🍕', name: 'pizza', keywords: ['pizza', 'fast food', 'italian'] },
    { emoji: '🥪', name: 'sandwich', keywords: ['sandwich', 'bread', 'lunch'] },
    { emoji: '🌮', name: 'taco', keywords: ['taco', 'mexican', 'fast food'] },
    { emoji: '🌯', name: 'burrito', keywords: ['burrito', 'mexican', 'wrap'] },
    { emoji: '🥗', name: 'green salad', keywords: ['salad', 'healthy', 'vegetable'] },
    { emoji: '🍝', name: 'spaghetti', keywords: ['pasta', 'spaghetti', 'italian'] },
    { emoji: '🍜', name: 'steaming bowl', keywords: ['ramen', 'noodles', 'soup'] },
    { emoji: '🍲', name: 'pot of food', keywords: ['pot', 'stew', 'soup'] },
    { emoji: '🍛', name: 'curry rice', keywords: ['curry', 'rice', 'spicy'] },
    { emoji: '🍣', name: 'sushi', keywords: ['sushi', 'fish', 'japanese'] },
    { emoji: '🍱', name: 'bento box', keywords: ['bento', 'japanese', 'lunch'] },
    { emoji: '🍙', name: 'rice ball', keywords: ['rice', 'onigiri', 'japanese'] },
    { emoji: '🍚', name: 'cooked rice', keywords: ['rice', 'food'] },
    { emoji: '🍧', name: 'shaved ice', keywords: ['ice', 'dessert', 'cold'] },
    { emoji: '🍨', name: 'ice cream', keywords: ['ice cream', 'dessert', 'cold'] },
    { emoji: '🍦', name: 'soft ice cream', keywords: ['ice cream', 'dessert', 'cone'] },
    { emoji: '🍰', name: 'shortcake', keywords: ['cake', 'dessert', 'sweet'] },
    { emoji: '🎂', name: 'birthday cake', keywords: ['cake', 'birthday', 'celebration'] },
    { emoji: '🍮', name: 'custard', keywords: ['pudding', 'custard', 'dessert'] },
    { emoji: '🍭', name: 'lollipop', keywords: ['candy', 'lollipop', 'sweet'] },
    { emoji: '🍬', name: 'candy', keywords: ['candy', 'sweet'] },
    { emoji: '🍫', name: 'chocolate bar', keywords: ['chocolate', 'candy', 'sweet'] },
    { emoji: '🍿', name: 'popcorn', keywords: ['popcorn', 'snack', 'movie'] },
    { emoji: '🍩', name: 'doughnut', keywords: ['donut', 'doughnut', 'sweet'] },
    { emoji: '🍪', name: 'cookie', keywords: ['cookie', 'sweet', 'dessert'] },
    { emoji: '☕', name: 'hot beverage', keywords: ['coffee', 'tea', 'hot', 'drink'] },
    { emoji: '🍵', name: 'teacup without handle', keywords: ['tea', 'drink', 'green tea'] },
    { emoji: '🥤', name: 'cup with straw', keywords: ['drink', 'soda', 'straw'] },
    { emoji: '🍺', name: 'beer mug', keywords: ['beer', 'drink', 'alcohol'] },
    { emoji: '🍻', name: 'clinking beer mugs', keywords: ['beer', 'cheers', 'toast'] },
    { emoji: '🍷', name: 'wine glass', keywords: ['wine', 'drink', 'alcohol'] },
    { emoji: '🍾', name: 'bottle with popping cork', keywords: ['champagne', 'celebration', 'party'] },
  ],
  travel: [
    { emoji: '🚗', name: 'automobile', keywords: ['car', 'vehicle', 'drive'] },
    { emoji: '🚕', name: 'taxi', keywords: ['taxi', 'cab', 'car'] },
    { emoji: '🚙', name: 'sport utility vehicle', keywords: ['suv', 'car', 'vehicle'] },
    { emoji: '🚌', name: 'bus', keywords: ['bus', 'vehicle', 'transport'] },
    { emoji: '✈️', name: 'airplane', keywords: ['airplane', 'plane', 'fly', 'travel'] },
    { emoji: '🚀', name: 'rocket', keywords: ['rocket', 'space', 'launch'] },
    { emoji: '🛸', name: 'flying saucer', keywords: ['ufo', 'alien', 'space'] },
    { emoji: '🚁', name: 'helicopter', keywords: ['helicopter', 'fly', 'aircraft'] },
    { emoji: '⛵', name: 'sailboat', keywords: ['sail', 'boat', 'sea'] },
    { emoji: '🚢', name: 'ship', keywords: ['ship', 'boat', 'cruise'] },
    { emoji: '🏠', name: 'house', keywords: ['house', 'home', 'building'] },
    { emoji: '🏡', name: 'house with garden', keywords: ['house', 'home', 'garden'] },
    { emoji: '🏢', name: 'office building', keywords: ['office', 'building', 'work'] },
    { emoji: '🏖', name: 'beach with umbrella', keywords: ['beach', 'sea', 'sand', 'vacation'] },
    { emoji: '🏝', name: 'desert island', keywords: ['island', 'desert', 'tropical'] },
    { emoji: '🌋', name: 'volcano', keywords: ['volcano', 'mountain', 'eruption'] },
    { emoji: '🏔', name: 'snow-capped mountain', keywords: ['mountain', 'snow', 'cold'] },
    { emoji: '🗽', name: 'statue of liberty', keywords: ['statue', 'liberty', 'new york'] },
    { emoji: '🏰', name: 'castle', keywords: ['castle', 'building', 'fortress'] },
  ],
  activities: [
    { emoji: '⚽', name: 'soccer ball', keywords: ['soccer', 'football', 'ball', 'sport'] },
    { emoji: '🏀', name: 'basketball', keywords: ['basketball', 'ball', 'sport'] },
    { emoji: '🏈', name: 'american football', keywords: ['football', 'ball', 'sport', 'american'] },
    { emoji: '⚾', name: 'baseball', keywords: ['baseball', 'ball', 'sport'] },
    { emoji: '🎾', name: 'tennis', keywords: ['tennis', 'ball', 'sport'] },
    { emoji: '🎱', name: 'pool 8 ball', keywords: ['pool', '8ball', 'billiards', 'game'] },
    { emoji: '🥊', name: 'boxing glove', keywords: ['boxing', 'glove', 'sport', 'fight'] },
    { emoji: '⛳', name: 'flag in hole', keywords: ['golf', 'sport', 'hole'] },
    { emoji: '🎯', name: 'direct hit', keywords: ['target', 'bullseye', 'dart'] },
    { emoji: '🎣', name: 'fishing pole', keywords: ['fishing', 'pole', 'fish'] },
    { emoji: '🏆', name: 'trophy', keywords: ['trophy', 'winner', 'award', 'champion'] },
    { emoji: '🥇', name: '1st place medal', keywords: ['gold', 'medal', 'first', 'winner'] },
    { emoji: '🎭', name: 'performing arts', keywords: ['theater', 'drama', 'masks', 'acting'] },
    { emoji: '🎨', name: 'artist palette', keywords: ['art', 'paint', 'palette', 'creative'] },
    { emoji: '🎬', name: 'clapper board', keywords: ['movie', 'film', 'cinema', 'clapper'] },
    { emoji: '🎤', name: 'microphone', keywords: ['microphone', 'sing', 'music', 'karaoke'] },
    { emoji: '🎧', name: 'headphone', keywords: ['headphone', 'music', 'audio'] },
    { emoji: '🎹', name: 'musical keyboard', keywords: ['piano', 'keyboard', 'music'] },
    { emoji: '🎸', name: 'guitar', keywords: ['guitar', 'music', 'rock'] },
    { emoji: '🎲', name: 'game die', keywords: ['dice', 'game', 'random'] },
    { emoji: '🎮', name: 'video game', keywords: ['game', 'video game', 'controller'] },
    { emoji: '🧩', name: 'puzzle piece', keywords: ['puzzle', 'piece', 'game'] },
  ],
  objects: [
    { emoji: '📱', name: 'mobile phone', keywords: ['phone', 'mobile', 'smartphone', 'cell'] },
    { emoji: '💻', name: 'laptop', keywords: ['laptop', 'computer', 'pc'] },
    { emoji: '📷', name: 'camera', keywords: ['camera', 'photo', 'picture'] },
    { emoji: '📺', name: 'television', keywords: ['tv', 'television', 'watch'] },
    { emoji: '⏰', name: 'alarm clock', keywords: ['alarm', 'clock', 'time', 'wake'] },
    { emoji: '💡', name: 'light bulb', keywords: ['bulb', 'light', 'idea', 'bright'] },
    { emoji: '💰', name: 'money bag', keywords: ['money', 'bag', 'dollar', 'rich'] },
    { emoji: '💎', name: 'gem stone', keywords: ['gem', 'diamond', 'jewel', 'precious'] },
    { emoji: '🔧', name: 'wrench', keywords: ['wrench', 'tool', 'fix'] },
    { emoji: '🔨', name: 'hammer', keywords: ['hammer', 'tool', 'build'] },
    { emoji: '⚙️', name: 'gear', keywords: ['gear', 'settings', 'mechanical'] },
    { emoji: '🔮', name: 'crystal ball', keywords: ['crystal', 'ball', 'fortune', 'magic'] },
    { emoji: '🔬', name: 'microscope', keywords: ['microscope', 'science', 'lab'] },
    { emoji: '🔭', name: 'telescope', keywords: ['telescope', 'space', 'stars'] },
    { emoji: '👑', name: 'crown', keywords: ['crown', 'king', 'queen', 'royal'] },
    { emoji: '🎩', name: 'top hat', keywords: ['hat', 'top hat', 'fancy', 'formal'] },
    { emoji: '🎓', name: 'graduation cap', keywords: ['graduation', 'cap', 'education', 'student'] },
    { emoji: '💍', name: 'ring', keywords: ['ring', 'jewelry', 'wedding', 'engagement'] },
  ],
  symbols: [
    { emoji: '❤️', name: 'red heart', keywords: ['heart', 'love', 'red'] },
    { emoji: '🧡', name: 'orange heart', keywords: ['heart', 'love', 'orange'] },
    { emoji: '💛', name: 'yellow heart', keywords: ['heart', 'love', 'yellow'] },
    { emoji: '💚', name: 'green heart', keywords: ['heart', 'love', 'green'] },
    { emoji: '💙', name: 'blue heart', keywords: ['heart', 'love', 'blue'] },
    { emoji: '💜', name: 'purple heart', keywords: ['heart', 'love', 'purple'] },
    { emoji: '🖤', name: 'black heart', keywords: ['heart', 'love', 'black'] },
    { emoji: '💔', name: 'broken heart', keywords: ['broken', 'heart', 'sad', 'breakup'] },
    { emoji: '💕', name: 'two hearts', keywords: ['hearts', 'love', 'two'] },
    { emoji: '💖', name: 'sparkling heart', keywords: ['heart', 'love', 'sparkle'] },
    { emoji: '☮️', name: 'peace symbol', keywords: ['peace', 'symbol', 'calm'] },
    { emoji: '❌', name: 'cross mark', keywords: ['x', 'cross', 'no', 'wrong'] },
    { emoji: '✅', name: 'check mark button', keywords: ['check', 'yes', 'correct', 'done'] },
    { emoji: '❗', name: 'exclamation mark', keywords: ['exclamation', 'mark', 'important'] },
    { emoji: '❓', name: 'question mark', keywords: ['question', 'mark', 'ask'] },
    { emoji: '⚠️', name: 'warning', keywords: ['warning', 'caution', 'alert'] },
    { emoji: '💯', name: 'hundred points', keywords: ['100', 'hundred', 'perfect', 'score'] },
    { emoji: '🎵', name: 'musical note', keywords: ['music', 'note', 'sound'] },
    { emoji: '🎶', name: 'musical notes', keywords: ['music', 'notes', 'song'] },
    { emoji: '🔴', name: 'red circle', keywords: ['red', 'circle', 'dot'] },
    { emoji: '🟠', name: 'orange circle', keywords: ['orange', 'circle', 'dot'] },
    { emoji: '🟡', name: 'yellow circle', keywords: ['yellow', 'circle', 'dot'] },
    { emoji: '🟢', name: 'green circle', keywords: ['green', 'circle', 'dot'] },
    { emoji: '🔵', name: 'blue circle', keywords: ['blue', 'circle', 'dot'] },
    { emoji: '💬', name: 'speech balloon', keywords: ['speech', 'bubble', 'chat', 'talk'] },
    { emoji: '💭', name: 'thought balloon', keywords: ['thought', 'bubble', 'think'] },
  ],
  flags: [
    { emoji: '🏳️', name: 'white flag', keywords: ['flag', 'white', 'surrender'] },
    { emoji: '🏴', name: 'black flag', keywords: ['flag', 'black'] },
    { emoji: '🏁', name: 'chequered flag', keywords: ['flag', 'race', 'finish'] },
    { emoji: '🚩', name: 'triangular flag', keywords: ['flag', 'red', 'warning'] },
    { emoji: '🏳️‍🌈', name: 'rainbow flag', keywords: ['flag', 'rainbow', 'pride', 'lgbt'] },
    { emoji: '🇺🇸', name: 'flag united states', keywords: ['flag', 'usa', 'america', 'us'] },
    { emoji: '🇬🇧', name: 'flag united kingdom', keywords: ['flag', 'uk', 'britain', 'england'] },
    { emoji: '🇨🇦', name: 'flag canada', keywords: ['flag', 'canada'] },
    { emoji: '🇦🇺', name: 'flag australia', keywords: ['flag', 'australia'] },
    { emoji: '🇯🇵', name: 'flag japan', keywords: ['flag', 'japan'] },
    { emoji: '🇩🇪', name: 'flag germany', keywords: ['flag', 'germany', 'deutschland'] },
    { emoji: '🇫🇷', name: 'flag france', keywords: ['flag', 'france', 'french'] },
    { emoji: '🇮🇹', name: 'flag italy', keywords: ['flag', 'italy', 'italian'] },
    { emoji: '🇪🇸', name: 'flag spain', keywords: ['flag', 'spain', 'spanish'] },
    { emoji: '🇲🇽', name: 'flag mexico', keywords: ['flag', 'mexico', 'mexican'] },
    { emoji: '🇧🇷', name: 'flag brazil', keywords: ['flag', 'brazil', 'brazilian'] },
    { emoji: '🇨🇳', name: 'flag china', keywords: ['flag', 'china', 'chinese'] },
    { emoji: '🇮🇳', name: 'flag india', keywords: ['flag', 'india', 'indian'] },
    { emoji: '🇰🇷', name: 'flag south korea', keywords: ['flag', 'korea', 'south korea'] },
    { emoji: '🇷🇺', name: 'flag russia', keywords: ['flag', 'russia', 'russian'] },
  ],
};

export const CATEGORY_META: Record<string, { label: string; icon: string }> = {
  recent:     { label: 'Recent',     icon: 'fas fa-clock' },
  smileys:    { label: 'Smileys',    icon: 'fas fa-smile' },
  people:     { label: 'People',     icon: 'fas fa-hand-paper' },
  animals:    { label: 'Animals',    icon: 'fas fa-paw' },
  food:       { label: 'Food',       icon: 'fas fa-utensils' },
  travel:     { label: 'Travel',     icon: 'fas fa-plane' },
  activities: { label: 'Activities', icon: 'fas fa-futbol' },
  objects:    { label: 'Objects',    icon: 'fas fa-lightbulb' },
  symbols:    { label: 'Symbols',    icon: 'fas fa-heart' },
  flags:      { label: 'Flags',      icon: 'fas fa-flag' },
};

export const RECENT_KEY = 'chatr_recent_emojis';
export const MAX_RECENT = 36;

